### ISSUE TITLE
Fix takedown procedure

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/polling_deploy#166]
Fails with ansible:

```sh
$ export AWS_PROFILE=wheredoivote
$ export ANSIBLE_HOST_KEY_CHECKING=False
$ ansible -u chris -i dynamic-inventory/ -b --become-user polling_stations tag_Env_prod -m shell -a "cd /var/www/polling_stations/code/ && ../env/bin/python manage.py teardown -c E06000041"
 [WARNING]: Found both group and host with same name: wdiv-micro-cache

34.254.181.145 | FAILED | rc=1 >>
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quitTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/polling_stations/code/polling_stations/apps/data_collection/management/commands/teardown.py", line 53, in handle
    apps.get_app_config("pollingstations"),
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/var/www/polling_stations/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/polling_stations/code/polling_stations/urls.py", line 11, in <module>
    from api.docs import ApiDocsView
  File "/var/www/polling_stations/code/polling_stations/apps/api/docs.py", line 1, in <module>
    from apiblueprint_view.views import ApiBlueprintView
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/apiblueprint_view/views.py", line 2, in <module>
    from .parser import ApibpParser
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/apiblueprint_view/parser.py", line 8, in <module>
    from draughtsman import parse
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/draughtsman/__init__.py", line 25, in <module>
    drafter = ffi.dlopen('drafter')
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/var/www/polling_stations/env/lib/python3.6/site-packages/cffi/api.py", line 823, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'drafter'non-zero return code
```

https://sentry.io/organizations/democracy-club-gp/issues/919856924/

Works over SSH:

```
$ ssh chris@xxx.xxx.xxx.xxx
Welcome to Ubuntu 18.04.2 LTS
...
$ sudo su polling_stations 
(env) polling_stations@ip-172-31-45-250:/var/www/polling_stations/code$ ./manage.py teardown -c E06000041
Deleting data for council E06000041...
..done
```

Set up a staging env and work out what is up. We definitely need to be on top of this ahead of polling day.

**Comment by chris48s** [comment]
Tried it again and now it works :man_shrugging:  Will have to keep an eye on it
